services:
  postgres:
    image: postgres:16
    container_name: sigmaql-db
    environment:
      POSTGRES_DB: sigmaqldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ilikepizza
    ports:
      - "5435:5432"